image: docker:18.09.7

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:18.09.7-dind

stages:
  - build
  - tests


build:
  stage: build

  script:
    - ./build-docker.sh

  artifacts:
    paths:
      - build-docker/libModulePython.so

  cache:
    key: ${CI_COMMIT_REF_SLUG}_build
    paths:
      - build-docker/
    policy: push

tests:
  stage: tests

  script:
    - ./run-tests.sh

  cache:
    key: ${CI_COMMIT_REF_SLUG}_build
    paths:
      - build-docker/
    policy: pull


